name: Terraform plan only

on:
  pull_request:
    branches: [ main, stagging, development ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:


permissions:
  id-token: write
  issues: write
  contents: read
  pull-requests: write
  checks: write
  actions: write

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      env-selected: ${{ steps.select-environment.outputs.env-selected }}
    steps:
      - name: "Select environment"
        id: select-environment
        run: |
          if [ "${{ github.base_ref }}" == "main" ]; then
            echo "Production environment selected for deployment - ${{ github.base_ref }} - ${{ github.ref_name }}"
            echo "env-selected=Production" >> $GITHUB_OUTPUT
          elif [ "${{ github.base_ref }}" == "stagging" ]; then
            echo "Stagging environment selected for deployment - ${{ github.base_ref }} - ${{ github.ref_name }}"
            echo "env-selected=Stagging" >> $GITHUB_OUTPUT
          elif [ "${{ github.base_ref }}" == "development" ]; then
            echo "Development environment selected for deployment - ${{ github.base_ref }} - ${{ github.ref_name }}"
            echo "env-selected=Development" >> $GITHUB_OUTPUT
          fi

  set-values:
    needs: [determine-environment]
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.env-selected }}      
    outputs:
      tf_token: ${{ steps.set-values.outputs.tf_token }}
      tf_workspace: ${{ steps.set-values.outputs.tf_workspace }}
    steps:
      - name: "Set values"
        id: set-values
        run: |
          echo "::set-output name=tf_token::${{ secrets.TF_TOKEN }}"
          echo "::set-output name=tf_workspace::${{ vars.TF_WORKSPACE }}"
        
  deployment:
    needs: [determine-environment, set-values]
    uses: ./.github/workflows/reusable-action.yml
    secrets: inherit
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
      ENVIRONMENT: ${{ needs.determine-environment.outputs.env-selected }}